"""Veterinary invoice extraction prompt (German). Migrated from prompt_building.get_full_prompt."""
from __future__ import annotations


def build_extract_prompt(
    *,
    ocr_text: str = "",
    subdocument_context: list[dict] | None = None,
    expected_items: int | None = None,
) -> str:
    """Build the extraction prompt for a single vet sub-invoice.

    `subdocument_context` carries the per-invoice animals detected during the
    analyze stage (formerly `animal_information`). The prompt body is copied
    verbatim from get_full_prompt(...) — do not paraphrase.
    """
    if subdocument_context:
        animals_section = "\n".join([f"{animal['name']} (Tierart: {animal['species']}, Rasse: {animal['breed']})"
                                    if animal['breed'] != ""
                                    else f"{animal['name']} (Tierart: {animal['species']})"
                                    for animal in subdocument_context])
        animals_section = f"Die folgenden Tiere werden in der Rechnung oder Quittung erwähnt: {animals_section}. Diese Information ist wichtig für die Extrahierung der Leistungen auf der Rechnung oder Quittung."
    else:
        animals_section = ""

    if expected_items and expected_items > 0:
        items_hint = f"WICHTIG: Diese Rechnung enthält voraussichtlich etwa {expected_items} Leistungen/Positionen. Wenn du weniger als {expected_items} Positionen findest, überprüfe nochmals den OCR-Text und das Bild — wahrscheinlich hast du Zeilen übersehen."
    else:
        items_hint = ""

    return (
"Du bist ein Experte für die Analyse von Tierarzt- und Tierphysiotherapie-Rechnungen.\n"
"Deine Aufgabe ist es, aus der untenstehenden Rechnung strukturierte Informationen zu extrahieren "
"und sie ausschließlich als gültiges JSON-Objekt im definierten Schema zurückzugeben.\n"
"Erfinde keine Werte. Wenn ein Feld nicht sicher ermittelt werden kann, gib null zurück und erkläre Unsicherheiten im Feld 'warnings'.\n"
f"{animals_section}\n"
f"{items_hint}\n"
"Die Rechnung ist als Bild (visuelle Referenz) sowie als OCR-Text aus zwei unabhängigen OCR-Systemen verfügbar. "
"Der OCR-Text ist zwischen Doppel-Pipes (||) angegeben und enthält zwei mit 'OCR Source A' und 'OCR Source B' gekennzeichnete Abschnitte. "
"Nutze beide OCR-Quellen, um Fehler zu erkennen und zu korrigieren. Bei Widersprüchen zwischen den OCR-Quellen überprüfe mit dem Bild.\n\n"
"OCR-Text:\n"
f"||\n{ocr_text}\n||\n\n"
"Regeln für die Extraktion:\n"
"1. Keine Halluzinationen: Nur Werte extrahieren, die im OCR- oder Bildinhalt sichtbar oder eindeutig ableitbar sind.\n"
"2. Wenn ein Feld fehlt oder nicht eindeutig ist → null.\n"
"3. Strings: ohne führende/trailing Leerzeichen.\n"
"4. Geldbeträge: nur Ziffern und Punkt, z. B. 36.31.\n"
"5. Datumsformat: YYYY-MM-DD.\n"
"6. Währung: ISO-4217-Code (z. B. \"EUR\").\n"
"7. Zeilen mit Summe, Endsumme, USt, MwSt, Gesamt, Saldo, Offen, Netto, Brutto → nicht als items übernehmen.\n"
"8. Eine Zeile mit klar erkennbarer Leistung oder Medikament UND einem Preis → ein items-Eintrag. Zeilen ohne Preis sind KEINE items. Wenn eine solche Zeile eine Diagnose, einen Befund oder eine klinische Beschreibung darstellt (z. B. 'Otitis externa', 'Ohren gesäubert und gespült', 'Verdacht auf Fraktur'), gehört sie in das Array 'diagnoses'. Rein erläuternde Zusätze zu einer Leistung (z. B. Dosierungshinweise) werden weder als item noch als Diagnose extrahiert.\n"
"9. Mengen und Einheiten extrahieren, wenn eindeutig (z. B. 10 Tabletten, 1 Flasche). Wenn nicht vorhanden → qty=null, unit=null.\n"
"10. GOT-Nummern: trenne in code, multiplier, raw; wenn keine gefunden → alle null.\n"
"11. Quellreferenzen: gib kurze Textausschnitte der extrahierten Zeile in source.snippet an.\n"
"12. Totals: normalisiere alle Zahlenwerte (Punkt als Dezimaltrennzeichen). Steuersatz und Steuerbetrag NUR extrahieren wenn explizit auf dem Dokument angegeben. Wenn kein Steuersatz/Steuerbetrag sichtbar ist → tax.rate=null, tax.amount=null.\n"
"13. Validierung: wenn totals.net, totals.tax.amount und totals.gross alle vorhanden sind, prüfe totals.net + totals.tax.amount ≈ totals.gross (Toleranz ±0.02).\n"
"14. IBAN (DE) = 22 Zeichen; BIC = 8 oder 11 Zeichen, upper-case. Die IBAN und BIC des Belegerstellers in 'sender' UND in 'payment' eintragen (identische Werte).\n"
"15. Die Leistungen (\"items\" unten) sollen in der Reihenfolge der Rechnung oder Quittung extrahiert werden. Meistens sind die Leistungen in Tabellenform angegeben. Achte daher besonders darauf ALLE Zeilen innerhalb von Tabellen genau zu analysieren und zu extrahieren. WICHTIG: Wenn eine Rechnung mehrere Behandlungstage enthält, wird dieselbe Leistung (z.B. \"Folgeuntersuchung\", \"Kaltplasmabehandlung\", \"Materialpauschale\") an jedem Tag separat aufgeführt. Jede Zeile ist ein eigener Eintrag — NICHT zusammenfassen oder deduplizieren.\n"
"16. Die sogenannten GOT-Codes (\"got\" unten) sind ein- bis vierstellige Zahlen, oft in Klammern dargestellt. Falls in dem Format 'GOT 1234' angegeben, dann nur die Ziffern zurückgeben. WICHTIG: Das Feld 'name' MUSS den originalen Zeilentext UNVERÄNDERT enthalten. Entferne GOT-Referenzen (z. B. '(GOT 1)', 'GOT 643') NICHT aus 'name' — die GOT-Extraktion in 'got' erfolgt ZUSÄTZLICH, nicht durch Herausschneiden aus 'name'.\n"
"17. Diagnosen: Sammle im Array 'diagnoses' alle auf dem Dokument explizit genannten Diagnosen, Befunde und klinischen Beschreibungen. Dazu gehören: Zeilen mit 'Diagnose:', 'Befund:' oder ähnlichen Bezeichnungen; klinische Beschreibungen ohne Preis in Leistungstabellen; eigenständige medizinische Feststellungen. NICHT aus Leistungsnamen ableiten (z. B. 'Otitisbehandlung' → NICHT 'Otitis' extrahieren). Wenn keine Diagnosen erkennbar sind → leeres Array [].\n\n"
"JSON-Ziel-Schema:\n"
"{{\n"
"\"type\": \"invoice|receipt|prescription|null\",\n"
"\"currency\": \"EUR|null\",\n"
"\"number\": \"string|null\",\n"
"\"issuedAt\": \"YYYY-MM-DD|null\",\n"
"\"serviceDates\": [\"YYYY-MM-DD\", \"...\"],\n"
"\"sender\": {{\n"
"  \"practiceName\": \"string|null\",\n"
"  \"address\": \"string|null\",\n"
"  \"postcode\": \"string|null\",\n"
"  \"city\": \"string|null\",\n"
"  \"country\": \"string|null\",\n"
"  \"contactPhone\": \"string|null\",\n"
"  \"contactMail\": \"string|null\",\n"
"  \"vatId\": \"string|null\",\n"
"  \"iban\": \"string|null\",\n"
"  \"bic\": \"string|null\"\n"
"}},\n"
"\"clinicians\": [\n"
"  {{ \"name\": \"string|null\", \"title\": \"string|null\" }}\n"
"],\n"
"\"payment\": {{\n"
"  \"iban\": \"string|null\",\n"
"  \"bic\": \"string|null\",\n"
"  \"bankName\": \"string|null\",\n"
"  \"dueDate\": \"YYYY-MM-DD|null\"\n"
"}},\n"
"\"recipient\": {{\n"
"  \"companyName\": \"string|null\",\n"
"  \"contactFirstname\": \"string|null\",\n"
"  \"contactName\": \"string|null\",\n"
"  \"street\": \"string|null\",\n"
"  \"postcode\": \"string|null\",\n"
"  \"city\": \"string|null\",\n"
"  \"country\": \"string|null\",\n"
"  \"contactPhone\": \"string|null\",\n"
"  \"contactMail\": \"string|null\"\n"
"}},\n"
"\"animals\": [\n"
"  {{ \"name\": \"string|null\", \"species\": \"string|null\", \"breed\": \"string|null\" }}\n"
"],\n"
"\"diagnoses\": [\"string\"],\n"
"\"items\": [\n"
"  {{\n"
"    \"name\": \"string|null\",  // Originaltext der Zeile UNVERÄNDERT, inkl. etwaiger GOT-Referenz wie '(GOT 1)'\n"
"    \"got\": {{ \"code\": \"string|null\", \"multiplier\": \"number|null\", \"raw\": \"string|null\" }},\n"
"    \"animal\": {{ \"name\": \"string|null\", \"species\": \"string|null\" }},\n"
"    \"qty\": \"number|null\",\n"
"    \"unit\": \"string|null\",\n"
"    \"unitPriceNet\": \"number|null\",\n"
"    \"lineTotalNet\": \"number|null\",\n"
"    \"serviceDate\": \"YYYY-MM-DD|null\",\n"
"    \"source\": {{ \"snippet\": \"string\" }}\n"
"  }}\n"
"],\n"
"\"totals\": {{\n"
"  \"net\": \"number|null\",\n"
"  \"tax\": {{ \"rate\": \"number|null\", \"amount\": \"number|null\" }},\n"
"  \"gross\": \"number|null\",\n"
"  \"discount\": \"number|null\"\n"
"}},\n"
"\"warnings\": [\"string\"]\n"
"}}\n\n"
"Nur das vollständige JSON-Objekt ausgeben, ohne Erklärung oder Markdown.\n"
"Wenn du unsicher bist, gib den wahrscheinlichsten Wert und eine kurze Begründung in warnings."
    )
